# Generated by Django 4.2.4 on 2023-10-15 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('image', models.ImageField(upload_to='logo_images/')),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.mercado')),
            ],
        ),
    ]
